- package.json
These being fixed to a particular version resulted in extra versions of
the dependency in consumers' node_modules tree/output bundles.
> Relax dependency versions

- src/model.ts
- src/scope.ts
- test/fixtures.ts
- test/integration/finders.test.ts
- test/integration/persistence-with-return-scope.test.ts
- test/unit/model-class-typings.test.ts
- test/unit/scope.test.ts
Graphiti now supports the ability to pass a lookup scope as part of a
data persistence operation and the additional data will be returned in
the response.  This wires up the necessary things in Spraypaint to be
able to take advantage.  Now you may pass a `returnScope` parameter to
any `save()` call:
```
let result = await Employee.find(1)
let employee = result.data
employee.firstName = 'Steve'
await employee.save({
returnScope: Employee.include(['department'])
})
console.log(employee.department.name) // => "Engineering"
```
> Allow data lookup in persistence operations

- package.json
- src/decorators.ts
- test/es6-compatibility/decorators.test.mjs
- test/es6-compatibility/mocha.opts
- test/es6-compatibility/test-setup.js
When the decorators were first setup, typescript and Babel had the same
API for implementing decorators.  Since then, TC39 has [evolved the
decorator API](https://github.com/tc39/proposal-decorators/blob/76af727310703b8d650d0f94220fa770a403a6bd/DETAILS.md).  This adds compatibility with the newer decorators.
Additionally, it adds an es6 compatibility smoke suite which will run
after the ESM module build.
The decorators code is getting pretty hairy with a number of code paths,
so I'd like to clean it up, but this at least gets it working an
unblocks a few users who are working in a modern babel setup.
> Get tc39 decorators working

- src/util/write-payload.ts
- test/fixtures.ts
- test/unit/write-payload.test.ts
Previously there was an issue when binding a Spraypaint model to a form
or otherwise allowing a number field to be set to an empty string.  This
would pass down to the backend and Graphiti would (correctly) blow up,
as it was receiving a string but expecting a number (or null, in this
case).  This will obey specyfing `Attr({type: Number})` in the model
definition.  When this receives an empty string during payload
serialization, it will write `null` instead.
This is a quick fix to a specific user problem.  There is a bigger
commit that needs to happen here with casting & payload
serialization/deserialization, but I'd like to get this in to fix the
immediate concern for now.
This addresses the concerns raised in https://github.com/graphiti-api/graphiti/pull/68
and moves the logic to the …
> Allow Number types not to write empty string

- src/util/write-payload.ts
- test/integration/nested-persistence.test.ts
If a non-persisted relationship is added and then it is marked for deletion,
it should not send that object as part of the payload.
> Don't send relationships and includes not persisted and marked for deletion

- src/decorators.ts
- src/index.ts
- src/model.ts
- src/util/deserialize.ts
- test/es6-compatibility/decorators.test.mjs
- test/fixtures.ts
- test/unit/decorators.test.ts
- test/unit/model.test.ts
Solves #16 
Click [here](https://jsonapi.org/format/#document-resource-object-links) for the specifications related to links in JSON:API
This is my first time coding in Typescript so I may not use all the features it offers.
In order to use my new decorator, one would follow this:
```ts
@Model()
export class PersonWithLinks extends SpraypaintBase {
static endpoint = "/v1/people_with_links"
static jsonapiType = "people_with_links"
@Link() self!: string
@Link() webView!: string
}
const person = await PersonWithLinks.find(123)
// Assuming that the pay load is
// {
//   data: {
//     id: "123",
//     type: "people_with_links",
//     links: {
//       self: "/v1/people_with_links/123",
//       web_view: "/people_with_links/123"
//     }
//   }
// }
person.links.self // value is …
```
> Support links as indicated in JSON:API specification

- src/model.ts
- test/integration/id-map.test.ts
- test/unit/model.test.ts
When doing [state syncing](https://www.graphiti.dev/js/state-syncing),
we wouldn't want to *automatically* sync relationships. If a Post A only
fetched comments matching text 'foo', we wouldn't want to Post B - which
adds a new comment without text 'foo' - to affect Post A's comments.
But there's still value in *manually* syncing relationships, when you're
aware of the issue but want things to sync-up in any case. You can now
do this with `#syncRelationships()`:
```ts
let author1 = await Author.find(1)
let author2 = await Author.find(1)
let book1 = new Book()
author2.books = [book1]
author2.syncRelationships()
author1.books # => [book1]
```
> Add syncRelationships()

- src/model.ts
- src/request.ts
- src/util/write-payload.ts
- test/integration/nested-persistence.test.ts
- test/integration/persistence.test.ts
In extremely rare cases, companies will not allow the PATCH HTTP verb.
For a longer explanation of this issue, see https://github.com/equivalent/scrapbook2/blob/master/archive/blogs/2016-12-12-put-vs-patch-vs-your-firewal.md
The solution is to send a POST alongside the `X-HTTP-Method-Override`
header. When the server adds `Rack::MethodOverride`, the header will
take precedence (making the server think it's a PATCH).
You can enable this behavior by setting the `patchAsPost` flag:
```ts
class ApplicationRecord extends SpraypaintBase {
// ... code ...
static patchAsPost = true
}
```
> Allow POST with _method PATCH

- src/deferred-action-callback.ts
- src/model.ts
- src/request.ts
- test/fixtures.ts
- test/integration/persistence.test.ts
Close #23 
Per the specification of JSON:API, if the server respond with 202 then that means it doesn't actually save or delete the resource yet. So the flag `isPersisted` should not change on the object.
> Handle response with status code 202 with potential background job details

- src/model.ts
- test/integration/rollback.test.ts
Hello there!
Previously the reset function overwrote the original attribute state with the current one making it a save() without a request and making all future calls to isDirty() invalid.
This should fix #21.
> Provide a way to reset attribute changes

- src/model.ts
- test/integration/fetch-middleware.test.ts
The default value for credentials is "same-origin", however this wasn't always the case.
Some older browsers implemented a version of the fetch specification where the default was "omit"
Because of this, those browsers omit the cookie when making requests, causing a 401 to be returned from the server
See https://github.com/github/fetch#sending-cookies
> Add credentials header into fetch request

- .tav.yml
- src/util/parameterize.ts
- test/integration/finders.test.ts
IE does not automatically encode, so let's do it for our users
automatically. This also checks if the value is already encoded (naively
checking for "%") and avoids if so.
> Encode param values when IE

- src/middleware-stack.ts
- src/request.ts
When information, required to make a new Fetch request, is retrieved with a Promise the value cannot be included in the filter.
With this commit both synchronous and asynchronous functions call be used to retrieve information.
This makes sense as Fetch is an asynchronous function as well.
Note: Credits to Sebastien Chopin (https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404) for a part of this code snippet.
> Make async/wait for middleware beforeFilters and afterFilters possible

- src/request.ts
Because afterFetch is returning a promise, the try catch statement won't work without await
How to test:
- Run tests, without this commit they will fail.
Sorry about that, I'm new to this framework. I didn't run the test suite with my previous MR :(
> Hotfix for async middleware

- src/request.ts
- test/integration/fetch-middleware.test.ts
Because originally response.json() was being called before throwing a ResponseError, a developer cannot access the original body to examine for specific (json) errors for correct error handling.
Reason: response.json() can only be called once per instance.
Therefore, a good practise for libraries is to clone the response before reading it to resolve this issue
More about this issue: https://stackoverflow.com/questions/40497859/reread-a-response-body-from-javascripts-fetch
About the clone method: https://developer.mozilla.org/en-US/docs/Web/API/Response/clone
> Enable developers to read response.json() when ResponseError is being thrown

- src/model.ts
- src/request.ts
- test/integration/persistence.test.ts
- test/unit/associations.test.ts
> Fix 204 response

- package.json
When https://github.com/graphiti-api/spraypaint.js/pull/50 was opened I noticed Travis is running an incomplete test suite. See [my comment here](https://github.com/graphiti-api/spraypaint.js/pull/50#issuecomment-553643079).
This PR makes sure all tests are run on the ci.
To confirm, compare this [log from a recent PR](https://travis-ci.org/graphiti-api/spraypaint.js/jobs/613578296?utm_medium=notification&utm_source=github_status) with the one [generated for this PR](https://travis-ci.org/graphiti-api/spraypaint.js/jobs/621327901?utm_medium=notification&utm_source=github_status).
> fix - ensure all tests are running on ci

- src/model.ts
- src/util/write-payload.ts
- test/integration/nested-persistence.test.ts
- test/unit/write-payload.test.ts
@nobitagit did a great job on https://github.com/graphiti-api/spraypaint.js/pull/47 fixing persistence of already persisted objects via a singular relationship (has one), however the situation still exists on plural relationships (has many).
> Persisting new resources with already persisted plural relationship members fails

- src/util/validation-error-builder.ts
- test/integration/validations.test.ts
The IDs need to be compared as strings, or graphiti_errors should be updated to compare as strings
Also ensures that a temp_id exists before comparing, avoiding comparing two undefined values
> Fixes comparison in validation error

- src/util/validation-error-builder.ts
- test/integration/validations.test.ts
Both #58 and #39 were recently merged when it looks like only #39 was needed. #58 is currently taking precedence and does not properly compare the IDs as strings, resulting in missing validation errors between graphiti and spraypaint. This removes the comparison merged from #58 so that the comparison from #39 is used which both ensures a temp id is defined and compares persisted IDs as strings.
Also, updated the test to reflect IDs as an integer since that's how they're returned by graphiti.
> Fix validation error ID comparison

- src/scope.ts
- test/unit/scope.test.ts
This branch aims to close #29 by adding support for respecting the `keyCase` configuration when making calls to the server.
To my knowledge, this is only lacking support for `merge`, which should be trivial. Will add once I dig a bit further into the ramifications of changing object keys in `this._associations`. I also noticed the `extraParams` scope method, which I couldn't find in the documentation. I haven't added support for that because I'm not sure what it does.
> Add support for keyCasing for server calls

- src/attribute.ts
- src/model.ts
- src/util/dirty-check.ts
- test/fixtures.ts
- test/integration/dirty-tracking.test.ts
- test/unit/attributes.test.ts
I had the same problem as issue #56 when checking dirty attributes. Default dirty checking does use JS strict equality and result in non-primitive types attributes being marked as dirty.
Since there is no "right answer" for this problem, I suggest allowing developers to override the way dirty attributes are detected.
Here is an example :
```ts
// My non-primitive type
export interface Coordinates{
lon: number;
lat: number;
}
// A custom dirty checker. I may also compare using `JSON.stringify()`
const dirtyCoordinatesChecker : DirtyChecker<Coordinates> = (prior: Coordinates, current: Coordinates) => (
(prior.lon !== current.lon) || (prior.lat !== current.lat)
)
@Model()
export class Place extends ApplicationRecord {
static jsonapiType = "place"
@Attr address!: string
// Register my custom …
```
> Add dirtyChecker to Attributes definitions

- esm-shims/isempty.js
- src/util/dirty-check.ts
- src/util/isempty.ts
The umd build is currently broken - https://travis-ci.org/github/graphiti-api/spraypaint.js/jobs/714764931
This should fix that.
Please see discussion around this issue:
https://graphiti-api.slack.com/archives/CTGRQALH0/p1597865269139100
https://graphiti-api.slack.com/archives/CTGRQALH0/p1597867117147600
> Fix umd build by providing an isempty shim

- src/model.ts
- test/unit/model.test.ts
Fixes https://github.com/graphiti-api/spraypaint.js/issues/66
> fix hasError returning false when one validation error exists

- src/model.ts
- src/util/deserialize.ts
- src/util/write-payload.ts
- test/unit/model.test.ts
- test/unit/write-payload.test.ts
JSON:API supports metadata at the individual resource level:
```json
{
"id": "1",
"type": "people",
"attributes": { "firstName": "Donald Budge" },
"meta": {
"editable": true
}
}
```
Spraypaint currently parses the JSON and stores the metadata in a private `__meta__` variable, but then does nothing with it.
This PR adds a getter that allows the metadata to be accessed by users:
```js
const { data } = await Person.find('1');
const editable = data.meta.editable;
...
```
This PR also allows the resource level metadata to be sent to the server during writes. This is useful when extra information is needed to be sent along with a resource where the extra data does not make sense as an `attribute`.
> Expose resource level metadata

- src/model.ts
- test/unit/model.test.ts
Currently you can't configure the fetch `credentials` header to change the way cookies are handled. This change would allow you to set a custom value.
> Allow configuration of credentials header

- src/index.ts
- src/model.ts
- src/proxies/collection-proxy.ts
- src/proxies/index.ts
- src/proxies/record-proxy.ts
- src/scope.ts
This adds a new `PersistedSpraypaintRecord` type which extends any
record type, definining the id as `string` instead of the initial
`string | undefined`. This will allow any record retrieved from
finders to be correctly typed with a defined id. This should avoid the
need for a bunch of boilerplate type guards when dealing with records
which are always coming from from finders. You can also use this to
manually cast a record after you save it:
```typescript
function createPerson(attrs): PersistedSpraypaintRecord<Person>
let person = new Person(attrs)
let success = await person.save()
if (success) {
person = person as PersistedSpraypaintRecord<Person>
} else {
// handle error
}
}
```
> Finder methods return "Persisted" type of a record
